2014-02-16 04:35:32,694 ERROR __main__ 'utf8' codec can't decode byte 0xb8 in position 9: invalid start byte
2014-02-16 04:36:04,407 ERROR __main__ 'utf8' codec can't decode byte 0xb8 in position 9: invalid start byte
2014-02-16 04:36:41,828 ERROR __main__ 'utf8' codec can't decode byte 0xb8 in position 9: invalid start byte
2014-02-16 04:36:41,828 ERROR __main__ <type 'exceptions.UnicodeDecodeError'> main.py 61
2014-02-16 04:44:07,436 ERROR __main__ 'utf8' codec can't decode byte 0xb8 in position 9: invalid start byte
2014-02-16 04:44:07,436 ERROR __main__ <type 'exceptions.UnicodeDecodeError'> main.py 61
2014-02-16 05:12:49,065 ERROR __main__ ''
2014-02-16 05:12:49,066 ERROR __main__ <class 'httplib.BadStatusLine'> main.py 61
2014-02-16 05:12:50,066 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:50,066 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:51,065 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:51,065 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:52,065 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:52,065 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:53,066 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:53,066 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:54,069 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:54,069 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:55,063 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:55,063 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:56,065 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:56,065 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:57,065 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:57,065 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:58,068 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:58,068 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:12:59,069 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:12:59,069 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:00,069 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:00,069 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:01,075 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:01,075 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:02,075 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:02,075 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:03,076 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:03,076 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:04,079 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:04,079 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:05,081 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:05,081 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:06,082 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:06,082 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:07,082 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:07,082 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:08,085 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:08,085 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:09,085 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:09,085 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:10,086 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:10,086 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:11,088 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:11,088 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:12,079 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:12,079 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:13,082 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:13,082 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:14,086 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:14,086 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:15,088 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:15,088 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:16,088 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:16,088 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:17,089 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:17,089 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:18,092 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:18,092 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:19,094 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:19,094 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:20,095 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:20,095 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:21,095 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:21,095 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:22,095 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:22,095 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:23,095 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:23,095 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:24,096 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:24,096 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:25,098 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:25,098 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:26,096 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:26,096 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:27,095 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:27,095 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:28,095 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:28,095 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:29,095 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:29,095 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:30,096 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:30,096 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:31,098 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:31,098 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:32,105 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:32,105 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:33,105 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:33,105 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:34,105 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:34,105 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:35,107 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:35,107 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:36,108 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:36,108 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:37,117 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:37,117 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:38,111 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:38,111 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:39,112 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:39,112 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:40,114 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:40,114 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:41,115 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:41,115 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:42,115 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:42,115 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:43,117 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:43,117 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:44,118 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:44,118 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:45,125 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:45,125 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:46,125 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:46,125 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:47,125 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:47,125 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:48,127 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:48,127 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:49,134 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:49,134 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:50,134 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:50,134 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:51,134 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:51,134 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:52,135 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:52,135 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:53,137 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:53,137 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:54,147 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:54,190 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:55,193 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:55,193 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:56,193 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:56,194 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:57,188 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:57,188 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:58,190 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:58,190 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:13:59,191 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:13:59,191 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:00,193 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:00,256 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:01,247 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:01,247 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:02,249 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:02,249 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:03,250 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:03,250 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:04,252 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:04,252 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:05,253 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:05,253 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:06,253 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:06,253 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:07,255 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:07,255 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:08,249 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:08,249 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:09,255 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:09,255 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:10,256 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:10,256 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:11,276 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:11,276 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:12,278 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:12,278 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:13,279 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:13,279 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:14,286 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:14,286 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:15,286 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:15,286 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:16,292 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:16,292 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:17,293 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:17,293 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:18,293 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:18,293 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:19,293 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:19,293 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:20,295 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:20,295 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:21,289 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:21,289 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:22,289 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:22,289 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:23,290 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:23,290 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:24,295 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:24,295 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:25,296 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:25,296 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:26,301 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:26,301 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:27,302 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:27,302 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:28,305 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:28,305 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:29,309 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:29,309 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:30,311 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:30,311 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:31,312 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:31,312 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:32,313 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:32,313 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:33,305 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:33,305 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:34,306 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:34,306 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:35,308 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:35,308 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:36,312 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:36,312 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:14:37,312 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-16 05:14:37,312 ERROR __main__ <class 'urllib2.URLError'> main.py 61
2014-02-16 05:15:44,132 ERROR __main__ HTTP Error 404: Not Found
2014-02-16 05:15:44,132 ERROR __main__ <class 'urllib2.HTTPError'> main.py 61
2014-02-16 05:17:00,960 ERROR __main__ HTTP Error 404: Not Found
2014-02-16 05:17:00,960 ERROR __main__ <class 'urllib2.HTTPError'> main.py 61
2014-02-16 05:33:59,204 ERROR __main__ 'utf8' codec can't decode byte 0xb8 in position 12: invalid start byte
2014-02-16 05:33:59,204 ERROR __main__ <type 'exceptions.UnicodeDecodeError'> main.py 61
2014-02-16 05:49:25,627 ERROR __main__ 'utf8' codec can't decode byte 0xb8 in position 5: invalid start byte
2014-02-16 05:49:25,627 ERROR __main__ <type 'exceptions.UnicodeDecodeError'> main.py 61
2014-02-16 05:57:32,348 ERROR __main__ 'utf8' codec can't decode byte 0xb8 in position 2: invalid start byte
2014-02-16 05:57:32,348 ERROR __main__ <type 'exceptions.UnicodeDecodeError'> main.py 61
2014-02-16 06:26:13,456 ERROR __main__ 'utf8' codec can't decode byte 0xb4 in position 9: invalid start byte
2014-02-16 06:26:13,456 ERROR __main__ <type 'exceptions.UnicodeDecodeError'> main.py 61
2014-02-16 06:39:57,267 ERROR __main__ 'utf8' codec can't decode byte 0xb4 in position 4: invalid start byte
2014-02-16 06:39:57,267 ERROR __main__ <type 'exceptions.UnicodeDecodeError'> main.py 61
2014-02-17 10:14:23,976 ERROR __main__ HTTP Error 500: Internal Server Error
2014-02-17 10:14:23,976 ERROR __main__ <class 'urllib2.HTTPError'> main.py 61
2014-02-18 15:59:31,615 ERROR __main__ <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2014-02-18 15:59:31,615 ERROR __main__ <class 'urllib2.URLError'> main.py 79
